name: GitHub Pages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT_DENDRON_PUBLIC_NOTES }}
          repository: harrisonfang/dendron-workspace
          ref: main

      - uses: pnpm/action-setup@v4
      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-nodejs-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install

      - name: Configure Dendron to use GitHub PAT for remote vaults
        run: sed -i -e 's/git@github.com:/https:\/\/${{ secrets.GH_PAT_DENDRON_PUBLIC_NOTES }}@github.com\//g' dendron.yml
      - name: Initialize Dendron workspace
        run: pnpm dendron workspace init

      - name: Initialize dependencies for publishing
        run: pnpm dendron publish init
      - name: Restore .next cache
        uses: actions/cache@v4
        with:
          path: .next/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('.next/yarn.lock', '.next/package-lock.json', '.next/**.[jt]s', '.next/**.[jt]sx') }}

      - name: Build and export notes
        run: pnpm dendron publish export --target github --yes
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
